name: 🐛 Bug Report
description: Report a bug or issue with the Electron + Next.js boilerplate
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        **Note**: If you're just trying to use this boilerplate to create apps, you might want the [main branch](https://github.com/yourusername/electron-nextjs-boilerplate/tree/main) instead.

  - type: checkboxes
    id: branch-check
    attributes:
      label: Branch Information
      description: Which branch are you using?
      options:
        - label: I'm using the **main branch** (for creating desktop apps)
        - label: I'm using the **dev branch** (for contributing to the infrastructure)
        - label: I'm not sure which branch I should be using

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Clone the repository...
        2. Run npm install...
        3. Execute npm run dev...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu)
        - Linux (Other)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (run `node --version`)
      placeholder: v22.16.0
    validations:
      required: true

  - type: input
    id: npm-version
    attributes:
      label: npm Version
      description: What version of npm are you using? (run `npm --version`)
      placeholder: 10.0.0
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: |
        Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots
        - Additional environment details
        - Related issues
        - Workarounds tried

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I am using a supported Node.js version (22.16.0+)
          required: true 